name: mask_r_cnn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - torch==1.9.0
  - torchvision==0.10.0
  - numpy==1.21.1
  - pandas==1.3.1
  - pillow==8.3.1
  - matplotlib==3.4.3
